CREATE TABLE "OAuthCode" ("id" TEXT PRIMARY KEY,"codeHash" TEXT NOT NULL UNIQUE,"userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,"clientId" TEXT NOT NULL,"redirectUri" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"usedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "OAuthCode_userId_idx" ON "OAuthCode"("userId");
